### ISSUE TITLE
Feature Request: Add byIcon finder

### ISSUE THREAD

**Issue by shibupanda** [truongsinh/appium-flutter-driver#6]
Hi, @truongsinh can we add **byIcon** flutter finder API?
https://api.flutter.dev/flutter/flutter_test/CommonFinders/byIcon.html

**Comment by truongsinh** [comment]
ha, seems that updated some new finders

**Comment by truongsinh** [comment]
I took a look, and it seems that your're requesting finder from `flutter_test` package, but I think `flutter driver` (on which `appium flutter driver` depends) only support finders as listed in `flutter_driver` package https://api.flutter.dev/flutter/flutter_driver/CommonFinders-class.html

**Comment by shibupanda** [comment]
Yes, you are correct. 
Is it needed to include flutter_test finder as well in appium?

**Comment by truongsinh** [comment]
Very doubtful. If we cannot run the test with `flutter driver`, then we cannot that test in `appium flutter driver`, because the architecture is very different. With `flutter test`, it's 1 process, and you can run the test without emulator. With `flutter driver`, it's 2 process, one "app-under-test" (AUT), the other is the "driver", and 2 process communicate via network.

**Comment by truongsinh** [comment]
Closing as won't do
